apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: "default"
  source:
    repoURL: https://github.com/alexmt/argocd-example-apps
    targetRevision: HEAD
    path: kustomize-guestbook
  destination:
    server: http://cluster-cluster1:8001
    namespace: default
