apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: laptop
        namespace: akuity-laptop
      - cluster: git-delegate
        namespace: akuity-git-delegate
  template:
    metadata:
      name: '{{cluster}}-guestbook'
      namespace: argocd
    spec:
      project: "default"
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps
        targetRevision: HEAD
        path: guestbook
      destination:
        cluster: '{{cluster}}'
        namespace: '{{namespace}}'
