apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: laptop
        url: http://cluster-laptop:8001
        namespace: akuity-laptop
      - cluster: git-delegate
        url: http://cluster-git-delegate:8001
        namespace: akuity-git-delegate
  template:
    metadata:
      name: '{{cluster}}-guestbook'
      namespace: argocd
      annotations:
        argocd-image-updater.argoproj.io/image-list: gcr.io/heptio-images/ks-guestbook-demo:^0.1
        argocd-image-updater.argoproj.io/write-back-method: git
    spec:
      project: "default"
      source:
        repoURL: https://github.com/alexmt/argocd-example-apps
        targetRevision: HEAD
        path: kustomize-guestbook
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
